# Generated by Django 3.0 on 2022-01-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metheqq_root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogrey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sulg', models.SlugField(max_length=255, unique=True)),
                ('campany_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campany_id', to='metheqq_root.Campany')),
            ],
            options={
                'verbose_name_plural': 'catogeryes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cat_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='home.Catogrey')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cerateby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
            ],
        ),
        migrations.CreateModel(
            name='catogry_permision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Catogrey', verbose_name='id')),
                ('marketer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metheqq_root.Marketers', verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='campany_permision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('campany_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metheqq_root.Campany')),
                ('marketer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metheqq_root.Marketers')),
            ],
        ),
    ]
