# Generated by Django 3.0 on 2022-01-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Campany',
            },
        ),
        migrations.CreateModel(
            name='Ecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecard', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MangerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iamge', models.ImageField(upload_to='')),
                ('word', models.TextField(max_length=255)),
                ('postion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marketers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrens', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_tts', models.BooleanField(default=False)),
                ('is_ts', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketersComisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisions', models.FloatField()),
                ('marketers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisions', to='metheqq_root.Marketers')),
            ],
        ),
    ]
